

var = {'name': None, 'owner': None, 'creation': None, 'modified': None, 'modified_by': None, 'parent': None,
       'parentfield': None, 'parenttype': None, 'idx': 0, 'docstatus': 0, 'title': None, 'naming_series': None,
       'customer': '2021-000283', 'customer_name': None, 'tax_id': None, 'pos_profile': None, 'is_pos': 0,
       'is_consolidated': 0, 'is_return': 0, 'is_debit_note': 0, 'update_billed_amount_in_sales_order': 0,
       'company': None, 'company_tax_id': None, 'posting_date': None, 'posting_time': None, 'set_posting_time': 0,
       'due_date': '2023-06-30', 'return_against': None, 'amended_from': None, 'm_psof': '07-2022-07',
       'psof': 'CB-000248', 'm_psof_name': '2963b6cd68', 'subs_period': 'July 2022', 'date_from': '2022-07-01',
       'date_to': '2022-07-31', 'subs_contract': 'SC000378', 'contract_start': '2022-07-01',
       'contract_end': '2023-06-30', 'project': None, 'cost_center': None, 'po_no': None, 'po_date': None,
       'customer_address': None, 'address_display': None, 'contact_person': None, 'contact_display': None,
       'contact_mobile': None, 'contact_email': None, 'territory': None, 'shipping_address_name': None,
       'shipping_address': None, 'company_address': None, 'company_address_display': None,
       'dispatch_address_name': None, 'dispatch_address': None, 'currency': None, 'conversion_rate': 0.0,
       'selling_price_list': None, 'price_list_currency': None, 'plc_conversion_rate': 0.0, 'ignore_pricing_rule': 0,
       'set_warehouse': None, 'set_target_warehouse': None, 'update_stock': 0, 'scan_barcode': None,
       'total_billing_amount': 0.0, 'total_billing_hours': 0.0, 'total_qty': 0.0, 'base_total': 0.0,
       'base_net_total': 0.0, 'total_net_weight': 0.0, 'total': 0.0, 'net_total': 0.0,
       'taxes_and_charges': 'Philippines Tax - CB', 'shipping_rule': None, 'tax_category': None,
       'other_charges_calculation': None, 'base_total_taxes_and_charges': 0.0, 'total_taxes_and_charges': 0.0,
       'loyalty_points': 0, 'loyalty_amount': 0.0, 'redeem_loyalty_points': 0, 'loyalty_program': None,
       'loyalty_redemption_account': None, 'loyalty_redemption_cost_center': None, 'apply_discount_on': None,
       'base_discount_amount': 0.0, 'additional_discount_account': None, 'additional_discount_percentage': 0.0,
       'discount_amount': 0.0, 'base_grand_total': 0.0, 'base_rounding_adjustment': 0.0, 'base_rounded_total': 0.0,
       'base_in_words': None, 'grand_total': 0.0, 'rounding_adjustment': 0.0, 'rounded_total': 0.0, 'in_words': None,
       'total_advance': 0.0, 'outstanding_amount': 0.0, 'disable_rounded_total': 0, 'write_off_amount': 0.0,
       'base_write_off_amount': 0.0, 'write_off_outstanding_amount_automatically': 0, 'write_off_account': None,
       'write_off_cost_center': None, 'allocate_advances_automatically': 0, 'ignore_default_payment_terms_template': 0,
       'payment_terms_template': None, 'cash_bank_account': None, 'base_paid_amount': 0.0, 'paid_amount': 0.0,
       'base_change_amount': 0.0, 'change_amount': 0.0, 'account_for_change_amount': None, 'tc_name': None,
       'terms': None, 'letter_head': None, 'group_same_items': 0, 'select_print_heading': None, 'language': None,
       'status': None, 'inter_company_invoice_reference': None, 'represents_company': None, 'customer_group': None,
       'campaign': None, 'is_internal_customer': 0, 'is_discounted': 0, 'source': None, 'debit_to': None,
       'party_account_currency': None, 'is_opening': None, 'c_form_applicable': None, 'c_form_no': None,
       'unrealized_profit_loss_account': None, 'remarks': None, 'sales_partner': None,
       'amount_eligible_for_commission': 0.0, 'commission_rate': 0.0, 'total_commission': 0.0, 'from_date': None,
       'to_date': None, 'auto_repeat': None, 'against_income_account': None, 'doctype': 'Sales Invoice', 'items': [
        {'name': None, 'owner': None, 'creation': None, 'modified': None, 'modified_by': None, 'parent': None,
         'parentfield': 'items', 'parenttype': 'Sales Invoice', 'idx': 1, 'docstatus': 0, 'barcode': None,
         'item_code': None, 'item_name': 'FIGHT SPORTS', 'customer_item_code': None, 'description': None,
         'item_group': None, 'brand': None, 'image': None, 'qty': 1.0, 'stock_uom': None, 'uom': 'Nos',
         'conversion_factor': 1.0, 'stock_qty': 0.0, 'price_list_rate': 0.0, 'base_price_list_rate': 0.0,
         'margin_type': None, 'margin_rate_or_amount': 0.0, 'rate_with_margin': 0.0, 'discount_percentage': 0.0,
         'discount_amount': 0.0, 'base_rate_with_margin': 0.0, 'rate': 100.0, 'amount': 0.0, 'item_tax_template': None,
         'base_rate': 0.0, 'base_amount': 0.0, 'pricing_rules': None, 'stock_uom_rate': 0.0, 'is_free_item': 0,
         'grant_commission': 0, 'net_rate': 0.0, 'net_amount': 0.0, 'base_net_rate': 0.0, 'base_net_amount': 0.0,
         'delivered_by_supplier': 0, 'income_account': None, 'is_fixed_asset': 0, 'asset': None, 'finance_book': None,
         'expense_account': None, 'discount_account': None, 'deferred_revenue_account': None, 'service_stop_date': None,
         'enable_deferred_revenue': 0, 'service_start_date': None, 'service_end_date': None, 'weight_per_unit': 0.0,
         'total_weight': 0.0, 'weight_uom': None, 'warehouse': None, 'target_warehouse': None,
         'quality_inspection': None, 'batch_no': None, 'incoming_rate': 0.0, 'allow_zero_valuation_rate': 0,
         'serial_no': None, 'item_tax_rate': None, 'actual_batch_qty': 0.0, 'actual_qty': 0.0, 'sales_order': None,
         'so_detail': None, 'sales_invoice_item': None, 'delivery_note': None, 'dn_detail': None, 'delivered_qty': 0.0,
         'cost_center': None, 'project': None, 'page_break': 0, 'doctype': 'Sales Invoice Item', '__islocal': 1}],
       'pricing_rules': [], 'packed_items': [], 'timesheets': [], 'taxes': [], 'advances': [], 'payment_schedule': [],
       'payments': [], 'sales_team': []}

var = {'name': 'ACC-SINV-2022-00003',
       'owner': 'Administrator',
       'creation': datetime.datetime(2022, 8, 12, 17, 7, 42, 629718),
       'modified': datetime.datetime(2022, 8, 12, 17, 7, 42, 629718),
       'modified_by': 'Administrator',
       'parent': None,
       'parentfield': None,
       'parenttype': None,
       'idx': 0,
       'docstatus': 0,
       'title': 'USA CABLE TV',
       'naming_series': 'ACC-SINV-.YYYY.-',
       'customer': '2021-000290',
       'customer_name': 'USA CABLE TV',
       'tax_id': None,
       'pos_profile': None,
       'is_pos': 0,
       'is_consolidated': 0,
       'is_return': 0,
       'is_debit_note': 0,
       'update_billed_amount_in_sales_order': 0,
       'company': 'Cable Boss',
       'company_tax_id': None,
       'posting_date': datetime.date(2022, 8, 12),
       'posting_time': datetime.timedelta(seconds=61662, microseconds=808488),
       'set_posting_time': 0,
       'due_date': datetime.date(2022, 8, 12),
       'return_against': None,
       'amended_from': None,
       'm_psof': None,
       'psof': None,
       'm_psof_name': None,
       'subs_period': None,
       'date_from': None,
       'date_to': None,
       'subs_contract': None,
       'contract_start': None,
       'contract_end': None,
       'project': None,
       'cost_center': None,
       'po_no': '',
       'po_date': None,
       'customer_address': 'USA CABLE TV-Office',
       'address_display': '3/ F, CSI Market Square A.B. Fernandez Ave. Dagupan City, Pangasinan<br>None<br>\nPhilippines<br>\n',
       'contact_person': None,
       'contact_display': None,
       'contact_mobile': None,
       'contact_email': None,
       'territory': 'All Territories',
       'shipping_address_name': '',
       'shipping_address': None,
       'company_address': None,
       'company_address_display': None,
       'dispatch_address_name': None,
       'dispatch_address': None,
       'currency': 'USD',
       'conversion_rate': 55.414431,
       'selling_price_list': 'Standard Selling',
       'price_list_currency': 'PHP',
       'plc_conversion_rate': 1.0,
       'ignore_pricing_rule': 0,
       'set_warehouse': None,
       'set_target_warehouse': None,
       'update_stock': 0,
       'scan_barcode': None,
       'total_billing_amount': 0.0,
       'total_billing_hours': 0.0,
       'total_qty': 1.0,
       'base_total': 27707.22,
       'base_net_total': 27707.22,
       'total_net_weight': 0.0,
       'total': 500.0,
       'net_total': 500.0,
       'taxes_and_charges': 'Philippines Tax - CB',
       'shipping_rule': None,
       'tax_category': 'Vat Inclusive',
       'other_charges_calculation': '<div class="tax-break-up" style="overflow-x: auto;">\n\t<table class="table table-bordered table-hover">\n\t\t<thead>\n\t\t\t<tr>\n\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\t<th class="text-left">Item</th>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\t<th class="text-right">Taxable Amount</th>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\t<th class="text-right">VAT @ 12.0</th>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t</thead>\n\t\t<tbody>\n\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td>NICKELODEON</td>\n\t\t\t\t\t<td class="text-right">\n\t\t\t\t\t\t\n\t\t\t\t\t\t\t$ 500.00\n\t\t\t\t\t\t\n\t\t\t\t\t</td>\n\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t\t\t<td class="text-right">\n\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t(12.0%)\n\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t$ 60.00\n\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\n\t\t</tbody>\n\t</table>\n</div>',
       'base_total_taxes_and_charges': 3324.87,
       'total_taxes_and_charges': 60.0,
       'loyalty_points': 0,
       'loyalty_amount': 0.0,
       'redeem_loyalty_points': 0,
       'loyalty_program': None,
       'loyalty_redemption_account': None,
       'loyalty_redemption_cost_center': None,
       'apply_discount_on': 'Grand Total',
       'base_discount_amount': 0.0,
       'additional_discount_account': None,
       'additional_discount_percentage': 0.0,
       'discount_amount': 0.0,
       'base_grand_total': 31032.08,
       'base_rounding_adjustment': 0.0,
       'base_rounded_total': 31032.08,
       'base_in_words': 'PHP Thirty One Thousand And Thirty Two and Eight Centavo only.',
       'grand_total': 560.0,
       'rounding_adjustment': 0.0,
       'rounded_total': 560.0,
       'in_words': 'USD Five Hundred And Sixty only.',
       'total_advance': 0.0,
       'outstanding_amount': 31032.08,
       'disable_rounded_total': 0,
       'write_off_amount': 0.0,
       'base_write_off_amount': 0.0,
       'write_off_outstanding_amount_automatically': 0,
       'write_off_account': None,
       'write_off_cost_center': None,
       'allocate_advances_automatically': 0,
       'ignore_default_payment_terms_template': 0,
       'payment_terms_template': None,
       'cash_bank_account': None,
       'base_paid_amount': 0.0,
       'paid_amount': 0.0,
       'base_change_amount': 0.0,
       'change_amount': 0.0,
       'account_for_change_amount': None,
       'tc_name': None,
       'terms': None,
       'letter_head': 'CableBossLogo',
       'group_same_items': 0,
       'select_print_heading': None,
       'language': 'en',
       'status': 'Draft',
       'inter_company_invoice_reference': None,
       'represents_company': None,
       'customer_group': '1',
       'campaign': None,
       'is_internal_customer': 0,
       'is_discounted': 0,
       'source': None,
       'debit_to': '11070005 - ACCTS. REC. - TRADE (ND) - CB',
       'party_account_currency': 'PHP',
       'is_opening': 'No',
       'c_form_applicable': 'No',
       'c_form_no': None,
       'unrealized_profit_loss_account': None,
       'remarks': 'No Remarks',
       'sales_partner': 'Gary Liwanag',
       'amount_eligible_for_commission': 27707.22,
       'commission_rate': 0.01,
       'total_commission': 2.77,
       'from_date': None,
       'to_date': None,
       'auto_repeat': None,
       'against_income_account': '40000001 - SALES - HBO 1 - CB',
       'doctype': 'Sales Invoice',
       'items': [{'name': '91a14c0940',
                  'owner': 'Administrator',
                  'creation': datetime.datetime(2022, 8, 12, 17, 7, 42, 629718),
                  'modified': datetime.datetime(2022, 8, 12, 17, 7, 42, 629718),
                  'modified_by': 'Administrator',
                  'parent': 'ACC-SINV-2022-00003',
                  'parentfield': 'items',
                  'parenttype': 'Sales Invoice',
                  'idx': 1,
                  'docstatus': 0,
                  'barcode': None,
                  'item_code': 'NICKELODEON',
                  'item_name': 'NICKELODEON',
                  'customer_item_code': None,
                  'description': 'NICKELODEON',
                  'item_group': 'CHANNELS',
                  'brand': None,
                  'image': '',
                  'qty': 1.0,
                  'stock_uom': 'Unit',
                  'uom': 'Unit',
                  'conversion_factor': 1.0,
                  'stock_qty': 1.0,
                  'price_list_rate': 0.0,
                  'base_price_list_rate': 0.0,
                  'margin_type': '',
                  'margin_rate_or_amount': 0.0,
                  'rate_with_margin': 0.0,
                  'discount_percentage': 0.0,
                  'discount_amount': 0.0,
                  'base_rate_with_margin': 0.0,
                  'rate': 500.0,
                  'amount': 500.0,
                  'item_tax_template': None,
                  'base_rate': 27707.22,
                  'base_amount': 27707.22,
                  'pricing_rules': None,
                  'stock_uom_rate': 500.0,
                  'is_free_item': 0,
                  'grant_commission': 1,
                  'net_rate': 500.0,
                  'net_amount': 500.0,
                  'base_net_rate': 27707.22,
                  'base_net_amount': 27707.22,
                  'delivered_by_supplier': 0,
                  'income_account': '40000001 - SALES - HBO 1 - CB',
                  'is_fixed_asset': 0,
                  'asset': None,
                  'finance_book': None,
                  'expense_account': 'Cost of Goods Sold - CB',
                  'discount_account': None,
                  'deferred_revenue_account': None,
                  'service_stop_date': None,
                  'enable_deferred_revenue': 0,
                  'service_start_date': None,
                  'service_end_date': None,
                  'weight_per_unit': 0.0,
                  'total_weight': 0.0,
                  'weight_uom': None,
                  'warehouse': 'Stores - CB',
                  'target_warehouse': None,
                  'quality_inspection': None,
                  'batch_no': None,
                  'incoming_rate': 0.0,
                  'allow_zero_valuation_rate': 0,
                  'serial_no': None,
                  'item_tax_rate': '{}',
                  'actual_batch_qty': 0.0,
                  'actual_qty': 0.0,
                  'sales_order': None,
                  'so_detail': None,
                  'sales_invoice_item': None,
                  'delivery_note': None,
                  'dn_detail': None,
                  'delivered_qty': 0.0,
                  'cost_center': 'Main - CB',
                  'project': None,
                  'page_break': 0,
                  'doctype': 'Sales Invoice Item'}],
       'pricing_rules': [],
       'packed_items': [],
       'timesheets': [],
       'taxes': [{'name': 'cd388da76c',
                  'owner': 'Administrator',
                  'creation': datetime.datetime(2022, 8, 12, 17, 7, 42, 629718),
                  'modified': datetime.datetime(2022, 8, 12, 17, 7, 42, 629718),
                  'modified_by': 'Administrator',
                  'parent': 'ACC-SINV-2022-00003',
                  'parentfield': 'taxes',
                  'parenttype': 'Sales Invoice',
                  'idx': 1,
                  'docstatus': 0,
                  'charge_type': 'On Net Total',
                  'row_id': None,
                  'account_head': '21990045 - VAT OUTPUT PAYABLE - CB',
                  'description': 'VAT @ 12.0',
                  'included_in_print_rate': 0,
                  'included_in_paid_amount': 0,
                  'cost_center': 'Main - CB',
                  'rate': 12.0,
                  'account_currency': 'PHP',
                  'tax_amount': 60.0,
                  'total': 560.0,
                  'tax_amount_after_discount_amount': 60.0,
                  'base_tax_amount': 3324.87,
                  'base_total': 31032.08,
                  'base_tax_amount_after_discount_amount': 3324.87,
                  'item_wise_tax_detail': '{"NICKELODEON":[12.0,3324.86586]}',
                  'dont_recompute_tax': 0,
                  'doctype': 'Sales Taxes and Charges'}],
       'advances': [],
       'payment_schedule': [{'name': '5893836390',
                             'owner': None,
                             'creation': datetime.datetime(2022, 8, 12, 17, 7, 42, 858528),
                             'modified': datetime.datetime(2022, 8, 12, 17, 7, 42, 858528),
                             'modified_by': 'Administrator',
                             'parent': 'ACC-SINV-2022-00003',
                             'parentfield': 'payment_schedule',
                             'parenttype': 'Sales Invoice',
                             'idx': 1,
                             'docstatus': 0,
                             'payment_term': None,
                             'description': None,
                             'due_date': datetime.date(2022, 8, 12),
                             'mode_of_payment': None,
                             'invoice_portion': 100.0,
                             'discount_type': None,
                             'discount_date': None,
                             'discount': 0.0,
                             'payment_amount': 560.0,
                             'outstanding': 560.0,
                             'paid_amount': 0.0,
                             'discounted_amount': 0.0,
                             'base_payment_amount': 31032.08,
                             'doctype': 'Payment Schedule'}],
       'payments': [],
       'sales_team': []}